### ISSUE TITLE
[Bug]: broadcom-wl-dkms fails to build on kernel 7.2.x: strncpy no longer declared in <linux/string.h>

### ISSUE THREAD

**Issue by vrajanap** [CachyOS/CachyOS-PKGBUILDS#1779]
### Package name

 broadcom-wl-dkms 

### Package version

6.30.223.271-49 

### Issue type

Build failure

## Package / version
broadcom-wl-dkms 6.30.223.271-49 (from cachyos repo)

## Environment
- Kernel: 7.2.2-1-cachyos (x86_64)
- Build toolchain: clang (LLVM=1), as used by the CachyOS kernel build

## Problem
After upgrading to kernel 7.2.2, `dkms` fails to build the `wl` module
(`dkms install` exits 10). The build log shows:

src/shared/linux_osl.c:863:10: error: call to undeclared library function 'strncpy' ...
src/wl/sys/wl_linux.c:1542:2: error: call to undeclared library function 'strncpy' ...

(in /var/lib/dkms/broadcom-wl/6.30.223.271/build/make.log)

## Root cause
Kernel 7.x removed the `strncpy()` declaration from `<linux/string.h>`
(in favor of `strscpy()`). Out-of-tree modules that still call `strncpy`
fail to compile when the kernel build enables
`-Wimplicit-function-declaration` as an error (clang default since
kernel 6.x/7.x).

The remaining unguarded `strncpy()` call sites in this package are:
- src/shared/linux_osl.c: `osl_strncpy()` and the MEM_FILENAME copy
- src/wl/sys/wl_linux.c: `dev->name`, `info->version`, monitor dev name

### Steps to reproduce

1. Install the latest kernel 
2. On the installation of the package, it runs into build errors 

> ==> dkms install --no-depmod broadcom-wl/6.30.223.271 -k 7.2.2-1-cachyos
> 
> Error! Bad return status for module build on kernel: 7.2.2-1-cachyos (x86_64)
> Consult /var/lib/dkms/broadcom-wl/6.30.223.271/build/make.log for more information.
> ==> WARNING: `dkms install --no-depmod broadcom-wl/6.30.223.271 -k 7.2.2-1-cachyos' exited 10
> 

### Relevant logs or error output

```shell
cat /var/lib/dkms/broadcom-wl/6.30.223.271/build/make.log 2>&1 | tail -80
In file included from src/wl/sys/wl_linux.c:85:
././src/wl/sys/wl_iw.h:73:9: warning: 'isprint' macro redefined [-Wmacro-redefined]
   73 | #define isprint(c) bcm_isprint(c)
      |         ^
/usr/lib/modules/7.2.2-1-cachyos/build/include/linux/ctype.h:30:9: note: previous definition is here
   30 | #define isprint(c)      ((__ismask(c)&(_P|_U|_L|_D|_SP)) != 0)
      |         ^
src/shared/linux_osl.c:863:10: error: call to undeclared library function 'strncpy' with type 'char *(char *, const char *, __size_t)' (aka 'char *(char *, const char *, unsigned long)'); ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  863 |         return (strncpy(d, s, n));
      |                 ^
src/shared/linux_osl.c:863:10: note: include the header <string.h> or explicitly provide a declaration for 'strncpy'
1 error generated.
make[3]: *** [/usr/lib/modules/7.2.2-1-cachyos/build/scripts/Makefile.build:289: src/shared/linux_osl.o] Error 1
make[3]: *** Waiting for unfinished jobs....
src/wl/sys/wl_linux.c:553:36: warning: cast from 'void (*)(wl_task_t *)' (aka 'void (*)(struct wl_task *)') to 'work_func_t' (aka 'void (*)(struct work_struct *)') converts to incompatible function type [-Wcast-function-type-strict]
  553 |                 MY_INIT_WORK(&wl->txq_task.work, (work_func_t)wl_start_txqwork);
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
././src/include/linuxver.h:112:53: note: expanded from macro 'MY_INIT_WORK'
  112 | #define MY_INIT_WORK(_work, _func)      INIT_WORK(_work, _func)
      |                                                          ^~~~~
/usr/lib/modules/7.2.2-1-cachyos/build/include/linux/workqueue.h:310:24: note: expanded from macro 'INIT_WORK'
  310 |         __INIT_WORK((_work), (_func), 0)
      |                               ^~~~~
/usr/lib/modules/7.2.2-1-cachyos/build/include/linux/workqueue.h:306:26: note: expanded from macro '__INIT_WORK'
  306 |                 __INIT_WORK_KEY(_work, _func, _onstack, &__key);        \
      |                                        ^~~~~
/usr/lib/modules/7.2.2-1-cachyos/build/include/linux/workqueue.h:298:20: note: expanded from macro '__INIT_WORK_KEY'
  298 |                 (_work)->func = (_func);                                \
      |                                  ^~~~~
src/wl/sys/wl_linux.c:558:39: warning: cast from 'void (*)(struct wl_task *)' to 'work_func_t' (aka 'void (*)(struct work_struct *)') converts to incompatible function type [-Wcast-function-type-strict]
  558 |                 MY_INIT_WORK(&wl->wl_dpc_task.work, (work_func_t)wl_dpc_rxwork);
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
././src/include/linuxver.h:112:53: note: expanded from macro 'MY_INIT_WORK'
  112 | #define MY_INIT_WORK(_work, _func)      INIT_WORK(_work, _func)
      |                                                          ^~~~~
/usr/lib/modules/7.2.2-1-cachyos/build/include/linux/workqueue.h:310:24: note: expanded from macro 'INIT_WORK'
  310 |         __INIT_WORK((_work), (_func), 0)
      |                               ^~~~~
/usr/lib/modules/7.2.2-1-cachyos/build/include/linux/workqueue.h:306:26: note: expanded from macro '__INIT_WORK'
  306 |                 __INIT_WORK_KEY(_work, _func, _onstack, &__key);        \
      |                                        ^~~~~
/usr/lib/modules/7.2.2-1-cachyos/build/include/linux/workqueue.h:298:20: note: expanded from macro '__INIT_WORK_KEY'
  298 |                 (_work)->func = (_func);                                \
      |                                  ^~~~~
src/wl/sys/wl_linux.c:794:3: warning: misleading indentation; statement is not part of the previous 'if' [-Wmisleading-indentation]
  794 |                 bar1_size = pci_resource_len(pdev, 2);
      |                 ^
src/wl/sys/wl_linux.c:792:2: note: previous statement is here
  792 |         if ((val & 0x0000ff00) != 0)
      |         ^
src/wl/sys/wl_linux.c:1221:28: warning: cast from 'void (*)(struct wl_task *)' to 'work_func_t' (aka 'void (*)(struct work_struct *)') converts to incompatible function type [-Wcast-function-type-strict]
 1221 |         MY_INIT_WORK(&task->work, (work_func_t)fn);
      |                                   ^~~~~~~~~~~~~~~
././src/include/linuxver.h:112:53: note: expanded from macro 'MY_INIT_WORK'
  112 | #define MY_INIT_WORK(_work, _func)      INIT_WORK(_work, _func)
      |                                                          ^~~~~
/usr/lib/modules/7.2.2-1-cachyos/build/include/linux/workqueue.h:310:24: note: expanded from macro 'INIT_WORK'
  310 |         __INIT_WORK((_work), (_func), 0)
      |                               ^~~~~
/usr/lib/modules/7.2.2-1-cachyos/build/include/linux/workqueue.h:306:26: note: expanded from macro '__INIT_WORK'
  306 |                 __INIT_WORK_KEY(_work, _func, _onstack, &__key);        \
      |                                        ^~~~~
/usr/lib/modules/7.2.2-1-cachyos/build/include/linux/workqueue.h:298:20: note: expanded from macro '__INIT_WORK_KEY'
  298 |                 (_work)->func = (_func);                                \
      |                                  ^~~~~
src/wl/sys/wl_linux.c:1542:2: error: call to undeclared library function 'strncpy' with type 'char *(char *, const char *, __size_t)' (aka 'char *(char *, const char *, unsigned long)'); ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1542 |         strncpy(info->version, EPI_VERSION_STR, sizeof(info->version));
      |         ^
src/wl/sys/wl_linux.c:1542:2: note: include the header <string.h> or explicitly provide a declaration for 'strncpy'
5 warnings and 1 error generated.
make[3]: *** [/usr/lib/modules/7.2.2-1-cachyos/build/scripts/Makefile.build:289: src/wl/sys/wl_linux.o] Error 1
make[2]: *** [/usr/lib/modules/7.2.2-1-cachyos/build/Makefile:2196: .] Error 2
make[1]: *** [/usr/lib/modules/7.2.2-1-cachyos/build/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/broadcom-wl/6.30.223.271/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/7.2.2-1-cachyos/build'
```

**Comment by oech3** [comment]
Report it to Arch linux's broadcom-wl-dkms too for testing/linux package.

**Comment by ptr1337** [comment]
Pushed wl-dkms with a fix, please verify

**Comment by vrajanap** [comment]
Thanks @ptr1337 !

**Comment by carljohnsonnewhampshire-hue** [comment]
@ptr1337, sorry I couldn't create a GitLab account because sign-up form requires credit card verification and requires attaching CVV code which I'm not willing to provide; I wanted to submit a bug report for broadcom-wl-dkms package on Arch Linux, it has the same issue described in this bug report, and still fails to compile against linux-7.2.4-arch1-2, I had to monkey-patch the broadcom-wl driver source manually with this shell script:
```sh
#!/bin/sh
set -eux

cd /usr/src
rm -rf broadcom-wl-*.bak
set -- broadcom-wl-*
if [ $# -gt 1 ]; then
  echo "error: more than one broadcom-wl source directory matched by glob: $*"
  exit 1
elif [ $# -eq 0 ]; then
  echo "error: no broadcom-wl source directory matched by glob"
  exit 1
fi
broadcom_wl_dir="$1"
cd "$broadcom_wl_dir"
cd ..
cp -r "$broadcom_wl_dir" "${broadcom_wl_dir}.bak"
cd "$broadcom_wl_dir.bak"
sed -i 's/strncpy(dev->name, intf_name, IFNAMSIZ-1);/strscpy(dev->name, intf_name, IFNAMSIZ);/' src/wl/sys/wl_linux.c
sed -i 's/strncpy(info->version, EPI_VERSION_STR, sizeof(info->version));/strscpy(info->version, EPI_VERSION_STR, sizeof(info->version));/' src/wl/sys/wl_linux.c
sed -i 's/strncpy(wlif->dev->name, wlif->name, strlen(wlif->name));/memcpy(wlif->dev->name, wlif->name, strlen(wlif->name));/' src/wl/sys/wl_linux.c
sed -i 's/strncpy(p->file, basename, BCM_MEM_FILENAME_LEN);/strscpy(p->file, basename, BCM_MEM_FILENAME_LEN);/' src/shared/linux_osl.c
sed -i 's/return (strncpy(d, s, n));/strscpy_pad(d, s, n); return (d);/' src/shared/linux_osl.c
if strncpy_calls="$(grep -n --color=always '\bstrncpy(' src/shared/linux_osl.c src/wl/sys/wl_linux.c)"; then
  echo "error: monkey-patching the source with sed didn't work, remaining strncpy() calls:"
  echo "$strncpy_calls"
  exit 1
fi
kern_rel="$(pacman -Q linux | awk '{sub("\\.arch", "-arch", $2); print $2}')"
dkms remove broadcom-wl/6.30.223.271 -k "$kern_rel"
dkms install broadcom-wl/6.30.223.271 -k "$kern_rel"
```
Is the fix coming to Arch Linux?
