### ISSUE TITLE
winesync-dkms 5.16-5 fails to build on kernel 6.17+

### ISSUE THREAD

**Issue by Idenroad** [CachyOS/CachyOS-PKGBUILDS#963]
## Description
The `winesync-dkms` package (version 5.16-5) fails to compile on recent kernels (6.17+) due to the removal of `no_llseek` in favor of `noop_llseek`.

## Error
src/drivers/misc/winesync.c:1186:13: error: use of undeclared identifier 'no_llseek'; did you mean 'noop_llseek'?

## Fix
In `/usr/src/winesync-5.16/src/drivers/misc/winesync.c`, line 1186:

**Replace:**
```c
.llseek         = no_llseek,
With:
.llseek         = noop_llseek,

Tested on
Kernel: 6.17.7-3-cachyos
Package: winesync-dkms 5.16-5
This fix allows the module to compile and install successfully.

Impact
This package is a dependency of proton-8-cachyos, so the issue affects users running recent kernels who need Wine/Proton for gaming.

**Comment by 1Naim** [comment]
https://github.com/CachyOS/linux-cachyos/issues/370.

And to elaborate further, winesync was replaced with ntsync. That is now upstream in both the linux kernel and wine.
